# global settings
SRCDIR	=	./originals

# helper functions
TO_ICON = 	convert $(1) -resize $(2)! PNG24:icon_$(2).png

# rules
all:	icons

icons:	
	$(call TO_ICON,$(SRCDIR)/icon.ai,29x29)
	$(call TO_ICON,$(SRCDIR)/icon.ai,36x36)
	$(call TO_ICON,$(SRCDIR)/icon.ai,45x45)
	$(call TO_ICON,$(SRCDIR)/icon.ai,48x48)
	$(call TO_ICON,$(SRCDIR)/icon.ai,50x50)
	$(call TO_ICON,$(SRCDIR)/icon.ai,57x57)
	$(call TO_ICON,$(SRCDIR)/icon.ai,58x58)
	$(call TO_ICON,$(SRCDIR)/icon.ai,60x60)
	$(call TO_ICON,$(SRCDIR)/icon.ai,64x64)
	$(call TO_ICON,$(SRCDIR)/icon.ai,72x72)
	$(call TO_ICON,$(SRCDIR)/icon.ai,90x90)
	$(call TO_ICON,$(SRCDIR)/icon.ai,96x96)
	$(call TO_ICON,$(SRCDIR)/icon.ai,100x100)
	$(call TO_ICON,$(SRCDIR)/icon.ai,114x114)
	$(call TO_ICON,$(SRCDIR)/icon.ai,135x135)
	$(call TO_ICON,$(SRCDIR)/icon.ai,144x144)
	$(call TO_ICON,$(SRCDIR)/icon.ai,480x480)
	$(call TO_ICON,$(SRCDIR)/icon.ai,512x512)
	$(call TO_ICON,$(SRCDIR)/icon.ai,1024x1024)
